- id: semgrep-docker-develop
  name: semgrep
  description: This hook runs semgrep:develop
  language: docker_image
  entry: returntocorp/semgrep:develop

- id: semgrep-docker
  name: semgrep
  description: This hook runs semgrep
  language: docker_image
  entry: returntocorp/semgrep:latest